const mySkills = [
  "frontend developer",
  "react",
  "typescript",
  "javascript",
  "d3",
  "html5",
  "css3",
  "sass",
  "data visualization",
  "open source",
  "redux",
  "next.js",
  "styled-components",
  "webpack",
  "react testing framework",
  "unit testing",
  "jest",
  "playwright",
  "solid code",
  "bem methodology",
  "javascript/typescript",
  "agile approach",
  "node.js",
  "docker",
  "tdd",
  "testing pyramid",
  "scrum",
  "git / git flow",
  "ci/cd",
  "react.js",
  "rest api",
  "ci/cd pipelines",
  "qa",
  "nextjs",
  "responsive",
  "performance",
  "reliability",
  "scalability",
  "problem-solving skills",
  "node",
  "apollo",
  "turborepo",
  "threejs",
  "three.js",
  "3d",
  "html/css",
  "ui kit",
  "data analytics",
  "agile mindset",
  "frontend framework",
  "devops",
  "solid",
  "xp",
  "ci/cd practices",
  "knowledge sharing",
  "git",
  "vercel",
  "api design",
  "npm",
  "storyboard",
  "agile",
  "kanban",
  "scss",
  "tailwind",
  "material ui",
  "independent work",
  "ui/ux design principles",
  "webgl",
  "graph visualization applications",
  "node/npm",
  "saas products",
  "keyboard navigation",
  "react testing library",
  "github",
  "continuous deployment techniques",
  "pull request reviews",
  "pair programming",
  "scrum processes",
  "automated tests",
  "internationalisation",
  "localisation",
  "responsive web design",
  "postcss/sass/scss",
  "javascript build tools",
  "quality",
  "communication",
  "teamwork",
  "angularjs",
  "nextjs/nuxtjs",
  "babel",
  "solid principles",
  "object-oriented programming",
  "oop",
  "agile environment",
  "asynchronous programming",
  "ui/ux principles",
  "version control systems",
  "visual studio",
  "vs code",
  "material design",
  "bootstrap",
  "agile methodology",
  "frontend architecture",
  "css in js",
  "accessible applications",
  "ux",
  "http",
  "continuous deployment",
  "react-dom",
  "lodash",
  "axios",
  "async",
  "eslint",
  "babel-loader",
  "react-router-dom",
  "react-redux",
  "moment",
  "node-sass",
  "prop-types",
  "yup",
  "react-query",
  "framer-motion",
  "react-icons",
  "react-hook-form",
  "@material-ui/core",
  "@emotion/react",
  "@emotion/styled",
  "fundamental programming concepts",
  "data structures",
  "algorithm design & analysis",
  "algorithm",
  "object-oriented design",
  "functional programming",
  "scripting languages",
  "compiled languages",
  "version control",
  "build tools",
  "continuous integration & continuous delivery (ci/cd)",
  "html, css & javascript",
  "container orchestration",
  "devsecops",
];

export default mySkills;
